# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: python:3.8

stages:
  - test
  - build
  - deploy
  - documentation

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  FOLDER: /

hugo:test:
  image: registry.gitlab.com/pages/hugo:latest
  stage: test
  script:
  - cd docs
  - hugo
  except:
  - master
    
.tests:
  stage: test

  script:
  - echo $FOLDER

  only:
    refs:
      - merge_requests
    changes:
    - $FOLDER
    - $FOLDER/**/*

.builds:
  stage: build

  only:
    refs:
    - master

  services:
    - docker:dind

  tags:
  -  docker-in-docker

  variables:
      http_proxy: http://wwwproxy.uni-muenster.de:80
      HTTP_PROXY: http://wwwproxy.uni-muenster.de:80
      HTTPS_PROXY: http://wwwproxy.uni-muenster.de:80
      https_proxy: http://wwwproxy.uni-muenster.de:80
      no_proxy: "docker,localhost,127.0.0.1,0.0.0.0,.wwu.de,.uni-muenster.de,.wwu.io,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,169.254.0.0/16"

      DOCKER_HOST: tcp://docker:2375
      DOCKER_DRIVER: overlay2


include:
  - '/RDS/circle1_adapters_and_ports/port_owncloud/.gitlab-ci.yml'
  - '/RDS/circle1_adapters_and_ports/port_zenodo/.gitlab-ci.yml'
  - '/RDS/circle2_use_cases/exporter/.gitlab-ci.yml'
  - '/RDS/circle3_central_services/metadata_capture/.gitlab-ci.yml'
  - '/RDS/circle3_central_services/project_manager/.gitlab-ci.yml'
  - '/RDS/circle3_central_services/token_service/.gitlab-ci.yml'

pages:
  image: registry.gitlab.com/pages/hugo:latest
  script:
  - cd docs
  - hugo
  - mv public ../
  artifacts:
    paths:
    - public
  only:
  - master
