image: python:3.8

stages:
  - test
  - build
  - deploy
  - documentation

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  FOLDER: ./

.tests:
  stage: test

  script:
    - cd $FOLDER
    - test -f requirements.txt && pip install -r requirements.txt
    - test -f requirements-dev.txt && pip install -r requirements-dev.txt
    - pip install pytest # if pytest not installed
    - python -m pytest

  tags:
  -  autoscaling

  except:
    refs:
      - master

  # https://gitlab.com/gitlab-org/gitlab/issues/8177
  # not supported currently
  #only:
  #  refs:
  #    - branches
  #  changes:
  #    - $FOLDER/*
  #    - $FOLDER/**/*

.builds:
  image: docker:19.03

  stage: build

  only:
    refs:
    - master

  services:
    - docker:dind

  tags:
  -  docker-in-docker

  variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_DRIVER: overlay2

  script: # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-docker-caching
    - cd $FOLDER
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_JOB_ID --tag $CI_REGISTRY_IMAGE:latest ./
    - docker build ./
    - docker push $CI_REGISTRY_IMAGE:$CI_JOB_ID
    - docker push $CI_REGISTRY_IMAGE:latest

include:
  - 'RDS/circle1_adapters_and_ports/port_owncloud/.gitlab-ci.yml'
  - 'RDS/circle1_adapters_and_ports/port_zenodo/.gitlab-ci.yml'
  - 'RDS/circle2_use_cases/exporter/.gitlab-ci.yml'
  - 'RDS/circle3_central_services/metadata_capture/.gitlab-ci.yml'
  - 'RDS/circle3_central_services/project_manager/.gitlab-ci.yml'
  - 'RDS/circle3_central_services/token_service/.gitlab-ci.yml'


# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
hugo:test:
  extends: .tests
  image: registry.gitlab.com/pages/hugo:latest
  
  variables:
    FOLDER: docs/

  script:
  - cd $FOLDER
  - hugo

  only:
    changes:
      - docs/*
      - docs/**/*

pages:
  image: registry.gitlab.com/pages/hugo:latest
  stage: documentation
  script:
  - cd docs
  - hugo
  - mv public ../
  artifacts:
    paths:
    - public
  only:
  - master
