image: python:3.8

stages:
  - test
  - build
  - deploy
  - documentation
  - pages

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  FOLDER: ./

.tests:
  stage: test

  script:
    - cd $FOLDER
    - test -f requirements.txt && pip install -r requirements.txt
    - test -f requirements-dev.txt && pip install -r requirements-dev.txt
    - pip install pytest # if pytest not installed
    - python -m pytest

  tags:
    - autoscaling

  except:
    refs:
      - master

  # https://gitlab.com/gitlab-org/gitlab/issues/8177
  # not supported currently
  #only:
  #  refs:
  #    - branches
  #  changes:
  #    - $FOLDER/*
  #    - $FOLDER/**/*

.builds:
  image: docker:19.03

  stage: build

  only:
    refs:
      - master

  services:
    - docker:dind

  tags:
    - docker-in-docker

  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2

  script: # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-docker-caching
    - cd $FOLDER
    - export DOCKERTAGNAME=$(echo "$CI_JOB_NAME" | cut -d":" -f2)
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY/$DOCKERTAGNAME:latest || true
    - docker build \
      --cache-from $CI_REGISTRY/$DOCKERTAGNAME:latest \
      --tag $CI_REGISTRY/$DOCKERTAGNAME:$CI_COMMIT_SHORT_SHA \
      --tag $CI_REGISTRY/$DOCKERTAGNAME:latest .
    - docker push $CI_REGISTRY/$DOCKERTAGNAME:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY/$DOCKERTAGNAME:latest

include:
  - "RDS/circle1_adapters_and_ports/port_zenodo/.gitlab-ci.yml"
  - "RDS/circle2_use_cases/token_service/.gitlab-ci.yml"
  - "RDS/circle3_central_services/token_service/.gitlab-ci.yml"

# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
hugo:test:
  extends: .tests
  image: registry.gitlab.com/pages/hugo:0.59.1

  variables:
    FOLDER: docs/

  script:
    - cd $FOLDER
    - hugo

  only:
    changes:
      - docs/*
      - docs/**/*

.documentation:
  stage: documentation
  only:
    refs:
      - master

pages:
  image: registry.gitlab.com/pages/hugo:0.59.1
  stage: pages
  script:
    - cd docs
    - hugo
    - mv public ../
  artifacts:
    paths:
      - public
  only:
    - master
