image: python:3.8

stages:
  - test
  - build
  - deploy
  - documentation

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  FOLDER: ./

.tests:
  stage: test

  script:
  - echo $FOLDER

  tags:
  -  autoscaling

  only:
    changes:
      - $FOLDER/*
      - $FOLDER/**/*

.builds:
  stage: build

  only:
    refs:
    - master

    changes:
      - $FOLDER/*
      - $FOLDER/**/*

  services:
    - docker:dind

  tags:
  -  docker-in-docker

  variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_DRIVER: overlay2

include:
  - 'RDS/circle1_adapters_and_ports/port_owncloud/.gitlab-ci.yml'
  - 'RDS/circle1_adapters_and_ports/port_zenodo/.gitlab-ci.yml'
  - 'RDS/circle2_use_cases/exporter/.gitlab-ci.yml'
  - 'RDS/circle3_central_services/metadata_capture/.gitlab-ci.yml'
  - 'RDS/circle3_central_services/project_manager/.gitlab-ci.yml'
  - 'RDS/circle3_central_services/token_service/.gitlab-ci.yml'


# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
hugo:test:
  extends: .tests
  image: registry.gitlab.com/pages/hugo:latest
  
  variables:
    FOLDER: docs/

  script:
  - cd $FOLDER
  - hugo

pages:
  image: registry.gitlab.com/pages/hugo:latest
  script:
  - cd docs
  - hugo
  - mv public ../
  artifacts:
    paths:
    - public
  only:
  - master
