.use_case_exporter:
  variables:
    FOLDER: RDS/circle2_use_cases/exporter

.tests_use_case_exporter:
  extends:
    - .tests
    - .use_case_exporter

  only:
    changes:
      - RDS/circle2_use_cases/exporter/*
      - RDS/circle2_use_cases/exporter/**/*

test:use_case_exporter3.6:
  image: python:3.6
  extends: .tests_use_case_exporter

test:use_case_exporter3.7:
  image: python:3.7
  extends: .tests_use_case_exporter

test:use_case_exporter3.8:
  image: python:3.8
  extends: .tests_use_case_exporter

build:use_case_exporter:
  extends:
    - .builds
    - .use_case_exporter
