variables:
    FOLDER: /RDS/circle1_adapters_and_ports/port_zenodo

test:port_zenodo3.6:
    image: python:3.6

    stage: test

    script:
    - cd $FOLDER
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest

    only:
        changes:
        - $FOLDER
    except:
    - master

test:port_zenodo3.7:
    image: python:3.7

    stage: test

    script:
    - cd $FOLDER
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest

    only:
        changes:
        - $FOLDER
    except:
    - master

test:port_zenodo3.8:
    image: python:3.8

    stage: test

    script:
    - cd $FOLDER
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest

    only:
        changes:
        - $FOLDER
    except:
    - master

build:port_zenodo:
    image: python:3.8

    stage: build

    script:
    - cd $FOLDER
    - pip install -r requirements.txt
    - docker build .


    only:
        refs:
        - master
        changes:
        - $FOLDER
    
