.tests_port_zenodo:
    extends: .tests
    variables:
        FOLDER: /RDS/circle1_adapters_and_ports/port_zenodo

    script:
    - cd $FOLDER
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest

test:port_zenodo3.6:
    extends: .tests_port_zenodo
    image: python:3.6

test:port_zenodo3.7:
    extends: .tests_port_zenodo
    image: python:3.7

test:port_zenodo3.8:
    extends: .tests_port_zenodo
    image: python:3.8

build:port_zenodo:
    image: python:3.8
    extends: .builds

    script:
    - cd $FOLDER
    - pip install -r requirements.txt
    - docker build .
    
