apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "circle2_port_service.fullname" . }}
  labels:
{{ include "circle2_port_service.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "circle2_port_service.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "circle2_port_service.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-mysql
          image: busybox
          command: ['sh', '-c', 'until nslookup circle3-token-storage; do echo waiting for mysql; sleep 2; done;']
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "FLASK_HOST_ADDRESS"
            value: "{{ .Values.environment.FLASK_HOST_ADDRESS }}"
          - name: CENTRAL-SERVICE_TOKEN-STORAGE
            valueFrom:
              configMapKeyRef:
                name: mservice
                key: CENTRAL_SERVICE_TOKEN_STORAGE
          - configMapRef:
            name: proxy
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
