variables:
    FOLDER: /RDS/circle3_central_services/metadata_capture

test:metadata_capture:
  image: python:3.8
  stage: test
  script:
  - whoami

  only:
    changes:
    - $FOLDER/*
  except:
    - master