# Default values for circle3_token_storage.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: zivgitlab.wwu.io/sciebo-rds/sciebo-rds/port_zenodo
  tag: connnectUI
  pullPolicy: Always

imagePullSecrets:
  - name: gitlab-registry
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 8080
  annotations:
     prometheus.io/scrape: 'true'

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

environment: 
  ZENODO_OAUTH_AUTHORIZE_URL: https://sandbox.zenodo.org%2Foauth%2Fauthorize%3Fscope%3Ddeposit%253Awrite%2520deposit%253Aactions%26redirect_uri%3Dhttps%253A%252F%252Fsciebords-dev.uni-muenster.de%252Ftoken-service%252Fredirect%26response_type%3Dcode%26client_id%3DfeYfqBVCfNDJTQyQRXWiJ8eoga99GxKzXYAZXvbm
  ZENODO_OAUTH_ACCESS_TOKEN_URL: https://sandbox.zenodo.org/oauth/token
  ZENODO_OAUTH_CLIEND_ID: feYfqBVCfNDJTQyQRXWiJ8eoga99GxKzXYAZXvbm
  # FIXME: secret needs to be set manually 
  # (https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables), 
  # but should be set via installations script or makefile
  zenodo-oauth-client-secret: ABC # Adjust me to valid values
  ZENODO_ADDRESS: https://sandbox.zenodo.org
