ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: sciebords-dev.uni-muenster.de
      paths:
      - /tracing

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local