openapi: 3.0.0
info:
  title: Port Owncloud
  version: '1.0'
  description: This document describes the interface of the port owncloud from the innermost circle of the rds architecture to the second circle.
  contact:
    name: Peter Heiss
    email: peter.heiss@uni-muenster.de
    url: 'https://www.research-data-services.org'
servers:
  - url: 'http://port-owncloud:3000'
paths:
  /:
    get:
      tags:
        - misc
      description: Shows all endpoints for this microservice.
      operationId: api.sitemap.index
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
              examples: {}
      summary: Get sitemap
    parameters: []
  '/file/{filepath}':
    parameters:
      - schema:
          type: string
        name: filepath
        in: path
        required: true
        description: url-encoded
    get:
      summary: Get file
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/octet-stream:
              schema:
                type: string
            application/json:
              schema:
                type: string
      operationId: ''
      description: Returns the file
      parameters:
        - schema:
            type: string
          in: query
          name: userId
          description: ''
          required: true
tags:
  - name: deposit
    description: All about depositions
  - name: creator
    description: All about user and deposition creators
  - name: misc
    description: Everything else.
