apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "circle1_port_zenodo.fullname" . }}
  labels:
{{ include "circle1_port_zenodo.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "circle1_port_zenodo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "circle1_port_zenodo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: "ZENODO_OAUTH_AUTHORIZE_URL"
            value: "{{ .Values.environment.ZENODO_OAUTH_AUTHORIZE_URL }}"
          - name: "ZENODO_OAUTH_ACCESS_TOKEN_URL"
            value: "{{ .Values.environment.ZENODO_OAUTH_ACCESS_TOKEN_URL }}"
          - name: "ZENODO_OAUTH_CLIEND_ID"
            value: "{{ .Values.environment.ZENODO_OAUTH_CLIEND_ID }}"
          - name: "ZENODO_ADDRESS"
            value: "{{ .Values.environment.ZENODO_ADDRESS }}"
          - name: "ZENODO_OAUTH_CLIENT_SECRET"
            valueFrom:
              secretKeyRef:
                name: zenodo-oauth-client-secret
                key: secret
          - name: USE_CASE_SERVICE_TOKEN_SERVICE
            valueFrom:
              configMapKeyRef:
                name: mservice
                key: USE_CASE_SERVICE_TOKEN_SERVICE
          - name: HTTP_PROXY
            valueFrom:
              configMapKeyRef:
                name: proxy
                key: http
          - name: HTTPS_PROXY
            valueFrom:
            configMapKeyRef:
              name: proxy
              key: http
          - name: http_proxy
            valueFrom:
              configMapKeyRef:
                name: proxy
                key: http
          - name: https_proxy
            valueFrom:
              configMapKeyRef:
                name: proxy
                key: http
          - name: no_proxy
            valueFrom:
              configMapKeyRef:
                name: proxy
                key: no_http_proxy
          - name: NO_PROXY
            valueFrom:
              configMapKeyRef:
                name: proxy
                key: no_http_proxy
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
