openapi: 3.0.0
info:
  title: central-service_token-storage
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    token:
      title: token
      type: object
      properties:
        id:
          type: string
        service:
          type: string
        access_token:
          type: string
          description: 'The token, which can be used as password for username in service.'
        username:
          type: string
