openapi: 3.0.0
info:
  version: '1.0'
  title: Port Invenio
  description: This describes the needed specification for circle 3.
  contact:
    name: Peter Heiss
    email: peter.heiss@uni-muenster.de
paths:
  /application_token:
    get:
      summary: Get application token
      tags:
        - token
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationToken'
      description: |-
        Returns everything needed for oauth 2.0 support.
        https://www.oauth.com/oauth2-servers/server-side-apps/authorization-code/
components:
  schemas:
    ApplicationToken:
      title: ApplicationToken
      type: object
      properties:
        client_secret:
          type: string
        client_id:
          type: string
          description: ''
        access_token_url:
          type: string
          description: ' Access token URL (POST)'
        authorize_url:
          type: string
          description: ' Authorize URL (GET)'
      x-tags:
        - token
      required:
        - authorize_url
        - access_token_url
        - client_id
        - client_secret
      description: |-
        This model describes the object, which represents all needed informations for oauth2.
        https://www.oauth.com/oauth2-servers/server-side-apps/authorization-code/
servers:
  - url: 'http://port-invenio:3000'
    description: ''
