.use_case_metadata:
  variables:
    FOLDER: RDS/circle2_use_cases/metadata

.tests_use_case_metadata:
  extends:
    - .tests
    - .use_case_metadata

test:use_case_metadata3.6:
  image: python:3.6
  extends: .tests_use_case_metadata

test:use_case_metadata3.7:
  image: python:3.7
  extends: .tests_use_case_metadata

test:use_case_metadata3.8:
  image: python:3.8
  extends: .tests_use_case_metadata

build:use_case_metadata:
  extends:
    - .builds
    - .use_case_metadata
  
  only:
    changes:
      - RDS/circle2_use_cases/metadata/*
      - RDS/circle2_use_cases/metadata/**/*
