openapi: 3.0.0
paths:
  /jsonschema:
    get:
      summary: Get jsonschema
      tags: []
      responses:
        '200':
          description: 'Responds with the jsonschema of datacite kernel 4.3 '
          content:
            application/json:
              schema:
                type: object
                properties:
                  kernelversion:
                    type: string
                  schema:
                    type: string
      operationId: ''
      description: |-
        Returns the used jsonschema.
        Currently this is datacite kernel 4.3

        https://raw.githubusercontent.com/datacite/schema/master/source/json/kernel-4.3/datacite_4.3_schema.json
  '/user/{user-id}/project/{project-index}':
    parameters:
      - schema:
          type: string
        name: user-id
        in: path
        required: true
      - schema:
          type: string
        name: project-index
        in: path
        required: true
    get:
      summary: Get the corresponding projectId
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  projectId:
                    type: integer
      operationId: api.UserProject.get
      description: This endpoint returns the projectId for the given user and the index of project. This is an endpoint for convenience.
info:
  version: '1.0'
  title: Exporter
  description: This service is responsible for any exporting functionality.
  contact:
    name: Peter Heiss
    url: 'https://www.research-data-services.org'
    email: peter.heiss@uni-muenster.de
servers:
  - url: 'http://use-case_metadata:3000/service'
    description: ''
