.use_case_token_service:
  variables:
    FOLDER: RDS/circle2_use_cases/token_service

.tests_use_case_token_service:
  extends:
    - .tests
    - .use_case_token_service

test:use_case_token_service3.6:
  image: python:3.6
  extends: .tests_use_case_token_service

test:use_case_token_service3.7:
  image: python:3.7
  extends: .tests_use_case_token_service

test:use_case_token_service3.8:
  image: python:3.8
  extends: .tests_use_case_token_service

build:use_case_token_service:
  extends:
    - .builds
    - .use_case_token_service

  only:
    changes:
      - RDS/circle2_use_cases/token_service/*
      - RDS/circle2_use_cases/token_service/**/*
