openapi: 3.0.0
info:
  version: '1.0'
  title: Central Service Project Manager
  description: 'This api describes the project endpoints, which manages projects and workflows.'
  contact:
    name: Peter Heiss
    email: peter.heiss@uni-muenster.de
paths:
  '/user/{user-id}':
    parameters:
      - schema:
          type: string
        name: user-id
        in: path
        required: true
    get:
      summary: List all projects from given user
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
        '404':
          description: Not Found
      operationId: ''
    post:
      summary: Add a project to user
      operationId: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
  '/user/{user-id}/project/{project-id}':
    parameters:
      - schema:
          type: string
        name: user-id
        in: path
        required: true
      - schema:
          type: string
        name: project-id
        in: path
        required: true
    get:
      summary: Get a Project
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
    delete:
      summary: Delete a Project
      responses:
        '204':
          description: No Content
    patch:
      summary: ''
      operationId: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
      description: 'Currently not implemented, because there are no function, which could be updated.'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
  '/user/{user-id}/project/{project-id}/exports':
    parameters:
      - schema:
          type: string
        name: user-id
        in: path
        required: true
      - schema:
          type: string
        name: project-id
        in: path
        required: true
    get:
      summary: List Project Exports
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Port'
    post:
      summary: ''
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Port'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Port'
  '/user/{user-id}/project/{project-id}/imports':
    parameters:
      - schema:
          type: string
        name: user-id
        in: path
        required: true
      - schema:
          type: string
        name: project-id
        in: path
        required: true
    get:
      summary: List Project Imports
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Port'
    post:
      summary: Create a Project Import
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Port'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Port'
  '/user/{user-id}/project/{project-id}/imports/{port-id}':
    parameters:
      - schema:
          type: string
        name: user-id
        in: path
        required: true
      - schema:
          type: string
        name: project-id
        in: path
        required: true
      - schema:
          type: string
        name: port-id
        in: path
        required: true
    get:
      summary: Get a Project Import
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Port'
        '404':
          description: Not Found
    delete:
      summary: Delete a Project Import
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
  '/user/{user-id}/project/{project-id}/exports/{port-id}':
    parameters:
      - schema:
          type: string
        name: user-id
        in: path
        required: true
      - schema:
          type: string
        name: project-id
        in: path
        required: true
      - schema:
          type: string
        name: port-id
        in: path
        required: true
    get:
      summary: Get a Project Export
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Port'
        '404':
          description: Not Found
    delete:
      summary: Delete a Project Export
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
  '/id/{project-id}':
    parameters:
      - schema:
          type: string
        name: project-id
        in: path
        required: true
    get:
      summary: Returns the corresponding project.
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
      operationId: ''
      description: ''
components:
  schemas:
    Project:
      title: Project
      description: This model represents a project.
      x-examples:
        example-1:
          id: '1'
          status: created
          import:
            - id: '1'
              port: port-owncloud
              properties:
                - type: filestorage
                  value: 'true'
          export:
            - id: '1'
              port: port-invenio
              properties:
                - type: filestorage
                  value: 'true'
                - type: metadata
                  value: 'true'
      anyOf:
        - type: object
          properties:
            userId:
              type: string
              description: This field will be set through the system.
            status:
              type: integer
              description: This field will be set through the system.
            portIn:
              type: array
              items:
                $ref: '#/components/schemas/Port'
            portOut:
              type: array
              items:
                $ref: '#/components/schemas/Port'
            projectId:
              type: integer
              description: This field will be set through the system.
            projectIndex:
              type: integer
              description: This field will be set through the system.
        - description: 'This is required, because connexion refused otherwise a connection without any requestBody.'
    Port:
      title: Port
      description: 'This model represents a port, which can be used in a project.'
      type: object
      properties:
        id:
          type: string
        port:
          type: string
        properties:
          type: array
          items:
            type: object
            description: ''
            properties:
              portType:
                type: string
                description: 'Only "metadata" and "filestorage" are currently supported as booleans. If type is not set, it defaults to false.'
              value:
                type: boolean
servers:
  - url: 'http://central-service_project-manager:3000/projects'
    description: ''
